# Generated by Django 5.0 on 2024-01-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'مقطع تحصیلی',
                'verbose_name_plural': 'مقاطع تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.level')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'ordering': ['level', 'name'],
                'unique_together': {('name', 'level')},
                'index_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30, null=True)),
                ('student_id', models.IntegerField(unique=True)),
                ('sex', models.CharField(default='مرد', max_length=3)),
                ('birth_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('student_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.level')),
            ],
            options={
                'verbose_name': 'دانش آموز',
                'verbose_name_plural': 'دانش آموزان',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.student')),
            ],
        ),
    ]
