# Generated by Django 5.0 on 2024-01-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'مقطع تحصیلی Level', 'verbose_name_plural': 'مقاطع تحصیلی'},
        ),
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'verbose_name': 'درس و دانش آموز', 'verbose_name_plural': 'جدول واسط دانش آموز و درس'},
        ),
        migrations.CreateModel(
            name='LevelStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.student')),
            ],
            options={
                'verbose_name': 'مقطع تحصیلی',
                'verbose_name_plural': 'دانش آموزان و مقاطع',
                'unique_together': {('student', 'level')},
                'index_together': {('student', 'level')},
            },
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
